### ISSUE TITLE
Request: Sort by newest in home page.

### ISSUE THREAD

**Issue by Coriana** [AXeL-dev/youtube-viewer#22]
This is a feature request, 

please allow videos to be sorted by publish time, rather than by their channels.

sometimes, i don't care which channel it is, i just want the newest videos published.

**Comment by AXeL-dev** [comment]
Hey,

For the newest videos you can use the "Recent" tab, you can also configure the recent videos seniority from the settings. Otherwise i think that the videos are already sorted by publish date per channel even on the "All view" in Home page, & the channels order is following the same order as in "Channels" page, so would you like to see the most recent videos on top, regardless of the channel?

**Comment by AXeL-dev** [comment]
Implemented in `v1.4.0`.
